<a href="https://colab.research.google.com/github/AriadnaVazquez/Metodos-Numericos-I/blob/main/Eliminaci%C3%B3n%20Gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

def gauss_elimination(A):
    """
    Implementa el método de eliminación Gaussiana con sustitución hacia atrás
    para resolver un sistema de ecuaciones lineales.

    Parámetros:
    A : np.ndarray
        Matriz aumentada del sistema lineal (nx(n+1)).

    Retorna:
    x : np.ndarray
        Vector de soluciones si existe una solución única.
    """
    n = A.shape[0]  # Número de incógnitas (filas de A)

    # Proceso de Eliminación Gaussiana
    print("Proceso de Eliminación Gaussiana:")
    for i in range(n - 1):
        # Selección del pivote
        pivot = A[i, i]
        if pivot == 0:
            raise ValueError("El pivote es cero. El sistema no tiene solución única.")

        # Eliminación de los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - factor * A[i, i:]

        # Imprimir la matriz en cada paso
        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")
        print(A)

    # Verificación del último pivote
    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe una solución única (último pivote nulo).")

    # Sustitución hacia atrás
    print("\nProceso de Sustitución Hacia Atrás:")
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        suma = np.dot(A[i, i + 1:n], x[i + 1:n])  # Suma de los términos conocidos
        x[i] = (A[i, -1] - suma) / A[i, i]
        print(f"x_{i + 1} = {x[i]:.4f}")  # Imprime el valor de x_i en cada paso

    return x


# ===========================
# Ejemplo de uso
# ===========================
if __name__ == "__main__":
    # Definimos la matriz aumentada A del sistema lineal dado:
    A = np.array([
        [1, -1, 2, -1, -8],
        [2, -2, 3, -3, -20],
        [1, 1, 1, 0, -2],
        [1, -1, 4, 3, 4]
    ], dtype=float)

    print("Matriz Aumentada Inicial:")
    print(A)

    try:
        # Llamamos a la función para resolver el sistema
        solution = gauss_elimination(A)

        # Imprimimos la solución final
        print("\nLa solución del sistema lineal es:")
        for i, val in enumerate(solution):
            print(f"x_{i+1} = {val:.4f}")
    except ValueError as e:
        print(e)

Matriz Aumentada Inicial:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]
Proceso de Eliminación Gaussiana:

Matriz después de la eliminación en la columna 1:
[[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
El pivote es cero. El sistema no tiene solución única.
