<a href="https://colab.research.google.com/github/AriadnaVazquez/Metodos-Numericos-I/blob/main/Factorizaci%C3%B3n%20LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def factorizacion_LU(A):
    """
    Implementa la factorización LU basada en el algoritmo 6.4.
    Parámetros:
        A (numpy.ndarray): Matriz cuadrada de tamaño n x n.
    Retorna:
        L (numpy.ndarray): Matriz triangular inferior.
        U (numpy.ndarray): Matriz triangular superior.
    Lanza:
        ValueError: Si la factorización no es posible.
    """
    n = A.shape[0]
    L = np.eye(n)  # Inicializar L como identidad
    U = np.zeros((n, n))  # Inicializar U como una matriz de ceros

    for i in range(n):
        # Paso 4: Seleccionar elementos de L y U para la diagonal
        suma_diag = sum(L[i, k] * U[k, i] for k in range(i))
        U[i, i] = A[i, i] - suma_diag

        if U[i, i] == 0:
            raise ValueError("Factorización imposible (diagonal cero en U).")

        for j in range(i + 1, n):
            # Paso 5: Calcular elementos de la i-ésima fila de U
            suma_u = sum(L[i, k] * U[k, j] for k in range(i))
            U[i, j] = A[i, j] - suma_u

            # Calcular elementos de la i-ésima columna de L
            suma_l = sum(L[j, k] * U[k, i] for k in range(i))
            L[j, i] = (A[j, i] - suma_l) / U[i, i]

    return L, U

# Matriz A
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

# Factorización LU
try:
    L, U = factorizacion_LU(A)
except ValueError as e:
    print("Error:", e)
    L, U = None, None

# Resultados
print("Matriz L (triangular inferior):")
print(L)
print("\nMatriz U (triangular superior):")
print(U)

Matriz L (triangular inferior):
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U (triangular superior):
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
